id: A6B8BD8FB
base_file: f456F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 04:58:16.878762
  last_modified_at: 2022-05-31 04:58:16.878766
