id: A6B8BD8FB
base_file: f1F5F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 04:58:16.876539
  last_modified_at: 2022-05-31 04:58:16.876547
